server:
  port: 8080

spring:
  jpa:      
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
 #   properties:
  #    hibernate:
  #      default-schema: public
  datasource:
    url: jdbc:mysql://localhost:3306/quanlybanhang
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
#logging:
 # level:
 #   org:
 #     springframework:
   #     security: TRACE

jwt:
  private-key-file: "D:/deshop-api/keys/private_key.pem"
  public-key-file: "D:/deshop-api/keys/public_key.pem"
